### ISSUE TITLE
Définir ce qu'il y a à faire

### ISSUE THREAD

**Issue by S-Stanley** [S-Stanley/ft_irc#1]
Le but de cette issue est de définir un plan, une liste de taches a réaliser pour réaliser ce projet.

Pour le moment je pense à:

- Setup le folder avec Makefile + main.cpp (https://github.com/S-Stanley/ft_irc/issues/2)
- Créer un basic serveur qui accept les connexions (https://github.com/S-Stanley/ft_irc/issues/4)
- Ajouter la vérification des arguments (port + password) et prévenir les erreurs + ajouter les tests nécessaires (https://github.com/S-Stanley/ft_irc/issues/3)
- Stocker les commandes et leur fonction associee dans une map (https://github.com/S-Stanley/ft_irc/issues/10)
- Stocker tous les clients dans une list chainée (https://github.com/S-Stanley/ft_irc/issues/5)
- Tester que le serveur irc reçoit bien les packets envoyées par le client (https://github.com/S-Stanley/ft_irc/issues/6)
- Permettre qu'un message reçu peut-être envoyer en broadcast a tous les clients (https://github.com/S-Stanley/ft_irc/issues/7)
- https://github.com/S-Stanley/ft_irc/issues/13
- https://github.com/S-Stanley/ft_irc/issues/14
- Filter les commandes et permettre de réaliser d'autres options (envoyées un message privé, changer son username, etc...)
- Avoir un type d'utilisateur operator avec des droits différents

**Comment by S-Stanley** [comment]
@JulesMaisonneuve qu'en penses-tu ?

**Comment by JulesMaisonneuve** [comment]
Très bon début, je rajouterai :

8. Avoir un type d'utilisateur operator avec des droits différents
