### ISSUE TITLE
Echec de la levée d'erreur dans le cas où une un nickname existe déjà

### ISSUE THREAD

**Issue by S-Stanley** [S-Stanley/ft_irc#24]
Dans le cas où un nickname existe déjà il faut renvoter une erreur. Cela fonctionne bien avec telnet mais pas avec irssi qui ne recoit pas le message (ou ne l'affiche pas).

**Comment by S-Stanley** [comment]
Irssi gere le cas et met un underscore au nickname, je close

**Comment by S-Stanley** [comment]
Le réouvre car meme si irssi donne un user different, on n'arrive tout de meme pas a se connecter au server

**Comment by JulesMaisonneuve** [comment]
Dans le cas où on fait /connect 127.0.0.1 port mdp test pour connecter un 1er user, et qu'on fait la même commande pour le 2eme ça rajoute un _ par défaut si le nick existe déjà (ex: test_ pour le nick du 2eme user)

**Comment by S-Stanley** [comment]
Je viens de faire un test, tant qu'on retourne mauvais nickname, irssi ne fait que envoyer avec un underscore en plus, il faudrait plutot que le server s'adapte a l'underscore (ou alors envoyer une erreur differente)
