### ISSUE TITLE
corriger le probleme d'espace de split

### ISSUE THREAD

**Issue by S-Stanley** [S-Stanley/ft_irc#33]
Quand on recupere les commandes envoyes par le client (et via telnet), le split fonctionne mal, exemple

```
PASS      password
```

au lieu de 

```
PASS password
```

Renvoie `ERR_NEEDMOREPARAMS` alors qu'il devrait valider la commande

**Comment by JulesMaisonneuve** [comment]
Dans le split, fichier utils.cpp, si pos vaut 0 alors on se situe sur un séparateur. Il faudrait l'effacer et continuer la boucle.
```
if (pos == 0)
{
    to_split.erase(0, 1);
    continue;
}
```
