### ISSUE TITLE
Erreur dans la demande de password quand plusieurs clients sont connectes

### ISSUE THREAD

**Issue by S-Stanley** [S-Stanley/ft_irc#35]
Quand un 2e client se connect, et qu'il ne tape pas son password, la fonctionnalite fonctionne bien par contre le message qui lui demande son password n'est pas envoye

**Comment by JulesMaisonneuve** [comment]
Pour résoudre le problème: dans la fonction `Server::run() ` du fichier server.cpp, repasser le booléen 'throw_err_password' à true au début de la boucle `while (i < (unsigned int)nfds)` dans le else et re-check dans le if: `if (throw_err_password)` que l'utilisateur n'est pas connecté: ` if (throw_err_password && get_user(i - 1, all_users)->connected == false)`
