### ISSUE TITLE
Quand 2 users join le même channel le programme crash

### ISSUE THREAD

**Issue by JulesMaisonneuve** [S-Stanley/ft_irc#54]
Ca viendrait de la boucle qui envoie un message lorsqu'un utilisateur rejoint un channel:

```
for (int it = 0; it < (chan->nb_users); it++)
{
    send_user_joined_channel(
        fds[chan->users_id[it]].fd,
        get_user(i -1, all_users)->nickname,
        get_user(i -1, all_users)->username,
        value[1]
    );
}
```

**Comment by S-Stanley** [comment]
@JulesMaisonneuve je n'ai pas le soucis sur macOS 😞 

Est-ce que tu peux envoyer le message d'erreur + retour de valgrind/fsanitize si possible pour que j'essaye de voir d'où ça peut venir stp ?

**Comment by JulesMaisonneuve** [comment]
@S-Stanley Le programme se termine juste sans rien renvoyer de spécial mais je me suis aperçu que parfois `fds[chan->users_id[it]]` valait `fds[0]` donc que ça envoyait le message sur le fd du serveur et en changeant `fds[chan->users_id[it]].fd]` en `fds[chan->users_id[it] + 1].fd]` tout fonctionne nickel avec 2+ utilisateurs, je ne sais pas si c'est une bonne solution

**Comment by S-Stanley** [comment]
@JulesMaisonneuve est-ce le probleme est toujours d'actu ?

**Comment by JulesMaisonneuve** [comment]
problème résolu
