### ISSUE TITLE
Quand il y a des espaces dans un message seul le premier mot est envoyé

### ISSUE THREAD

**Issue by JulesMaisonneuve** [S-Stanley/ft_irc#77]
Il faudrait peut-être reformer le message avant de l'envoyer

**Comment by S-Stanley** [comment]
@JulesMaisonneuve est-ce que c'est lié a l'issue https://github.com/S-Stanley/ft_irc/issues/82 ?

**Comment by JulesMaisonneuve** [comment]
@S-Stanley Oui

**Comment by S-Stanley** [comment]
> @S-Stanley Oui

D'accord je close le doublon #82

**Comment by S-Stanley** [comment]
Je viens de regarder:

On utilise value[2] donc un seul mot or il faudrait concatener. Par exemple avec une fonction comme celle-ci:

```cpp
std::string append_to_string(std::string *arr, unsigned int key)
{
    std::string to_return;

    for (int i = key; i < arr->length(); i++)
    {
        to_return.append(arr[i]);
        if (i + 1 != arr->length())
            to_return.append(" ");
    }
    return (to_return);
}
```

Cependant il y a un prob dans la fonction qui split car j'ai l'impression qu'elle ne renvoit pas le dernier mot.
